---

snmp:
    snmp_community: "amazing"

ospf:
    ospf_rid: 3.3.3.3
bgp:
    asn: "65001"
    router_id: 3.3.3.3
    update_source: "Loopback1"
    route_reflector: False
    neighbors:
        - 1.1.1.1
        - 2.2.2.2
        - 4.4.4.4