---

R1:
    hostname: 192.168.132.101
    groups:
        - cisco_iosxeiol

R2:
    hostname: 192.168.132.102
    groups:
       - cisco_iosxeiol

R3:
    hostname: 192.168.132.103
    groups:
        - cisco_iosxeiol

R4:
    hostname: 192.168.132.104
    groups:
       - cisco_iosxeiol

CSR5:
    hostname: 192.168.132.105
    groups:
        - cisco_iosxe

vMX1:
    hostname: 192.168.132.106
    groups:
        - junos

